# reporter.py - post comments to GitHub PR using PyGithub client (installation token)
import time

def post_review_comments(gh_client, owner, repo_name, pr_number, findings, summary):
    repo = gh_client.get_repo(f"{owner}/{repo_name}")
    pr = repo.get_pull(pr_number)

    # Create a review draft containing summary, then individual comments
    body = f"**AI PR Review (Llama)**\n\n{summary}\n\n_This review was generated by an automated agent._"
    try:
        pr.create_issue_comment(body)
    except Exception as ex:
        print('Failed to post summary comment:', ex)

    # Post inline review comments in one "review" (if any findings)
    if findings:
        comments = []
        for f in findings:
            # GitHub's create_review expects 'path' and 'position' or 'line' with commit_id.
            # We'll post per-file comments using create_review_comment on latest commit.
            comments.append(f)
        try:
            latest_commit = list(pr.get_commits())[-1]
            for c in comments:
                try:
                    pr.create_review_comment(body=c.get('message'), commit_id=latest_commit.sha, path=c.get('file'), line=c.get('line'))
                except Exception as e:
                    print('Failed to post inline comment:', e)
        except Exception as ex:
            print('Failed to post inline comments:', ex)
